name: Convert README to PDF
on:
  push:
    paths:
      - "README.md"
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Install Dependencies (Pandoc, LaTeX, and SVG tools)
        run: |
          sudo apt update
          sudo apt install -y pandoc texlive-xetex librsvg2-bin texlive-fonts-recommended

      - name: Convert README.md to PDF
        run: |
          pandoc README.md \
            -o MPI_CLUSTER_DOC_manascb1344.pdf \
            --pdf-engine=xelatex \
            -V geometry:"margin=1in" \
            -V mainfont="Arial" \
            -V monofont="DejaVu Sans Mono" \
            -V fontsize=13pt \
            -V documentclass=article \
            --toc
      
      - name: Commit and Push PDF
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add MPI_CLUSTER_DOC_manascb1344.pdf
          git commit -m "Auto-generate PDF from README.md"
          git push
        continue-on-error: true